import { Injectable, Logger } from "@nestjs/common";
import { ConfigService } from "@nestjs/config";
import { Octokit } from "@octokit/rest";
import { createAppAuth } from "@octokit/auth-app";

/**
 * Thrown when `ensureRepoExists` finds the repo name is already taken by a
 * repo not generated by this provisioning run (HTTP 422 from generate).
 */
export class RepoNameConflictError extends Error {
  constructor(org: string, name: string) {
    super(`Repository ${org}/${name} already exists and is not owned by this provisioning`);
    this.name = "RepoNameConflictError";
  }
}

function sleep(ms: number): Promise<void> {
  return new Promise((resolve) => setTimeout(resolve, ms));
}

// Extract the env-var key from a placeholder line. Accepts:
//   "# FOO=..." / "# FOO = ..." / "FOO=..." / "  #FOO=..."
// Returns null for lines without an `KEY=` pattern.
function extractKeyFromLine(line: string): string | null {
  const m = line.match(/^\s*#?\s*([A-Z0-9_]+)\s*=/i);
  return m ? m[1] : null;
}

function extractEnvKeys(content: string): Set<string> {
  const keys = new Set<string>();
  for (const line of content.split("\n")) {
    const k = extractKeyFromLine(line);
    if (k) keys.add(k);
  }
  return keys;
}

@Injectable()
export class GitHubService {
  private logger = new Logger(GitHubService.name);
  octokit: Octokit;
  private readonly appId?: string;
  private readonly privateKey?: string;
  private readonly installationId?: string;
  private readonly pat?: string;

  constructor(private configService: ConfigService) {
    const config = this.configService.getOrThrow("modules.github");
    this.appId = config.appId;
    this.privateKey = config.privateKey;
    this.installationId = config.installationId;
    this.pat = config.auth;

    if (this.appId && this.privateKey && this.installationId) {
      // GitHub App mode: mint an installation token per request via
      // @octokit/auth-app. The PEM private key is stored in env with literal
      // `\n` sequences; restore real newlines before handing to the auth lib.
      const privateKey = this.privateKey.replace(/\\n/g, "\n");
      this.octokit = new Octokit({
        authStrategy: createAppAuth,
        auth: {
          appId: this.appId,
          privateKey,
          installationId: Number(this.installationId),
        },
        userAgent: config.userAgent ?? "saas-starter",
      });
      this.logger.log("GitHub Octokit initialized with GitHub App authentication");
    } else if (this.pat) {
      // PAT mode (transition / single-user use).
      this.octokit = new Octokit({
        auth: this.pat,
        userAgent: config.userAgent ?? "saas-starter",
      });
      this.logger.log("GitHub Octokit initialized with PAT authentication");
    } else {
      this.logger.warn("GitHub credentials not configured (no App triplet nor PAT)");
    }
  }

  /** Whether enough credentials are present to perform provisioning. */
  isConfigured(): boolean {
    return Boolean((this.appId && this.privateKey && this.installationId) || this.pat);
  }

  /**
   * Ensure a private repo exists under `org` named `name`, generated from the
   * template `(tplOwner, tplRepo)`. Idempotent:
   *   - GET repo → 200: skip, return existing clone_url.
   *   - 404: POST generate (private:true).
   *   - generate 422: name already taken by an unowned repo → throw.
   * generate returns 202; repo contents may 404 briefly afterwards, so we
   * retry GET a few times before returning so callers can immediately upsert.
   */
  async ensureRepoExists(
    org: string,
    name: string,
    tplOwner: string,
    tplRepo: string,
    description?: string,
  ): Promise<{ cloneUrl: string; generated: boolean }> {
    // 1. Already exists?
    try {
      const { data } = await this.octokit.repos.get({ owner: org, repo: name });
      return { cloneUrl: data.clone_url, generated: false };
    } catch (e: any) {
      if (e.status !== 404) throw e;
    }

    // 2. Generate from template. 422 here means the name is taken by a repo
    //    we don't own (race / pre-existing) — surface as a typed error.
    let gen: { clone_url: string };
    try {
      const resp = await this.octokit.repos.createUsingTemplate({
        template_owner: tplOwner,
        template_repo: tplRepo,
        name,
        owner: org,
        description,
        private: true,
      });
      gen = resp.data;
    } catch (e: any) {
      if (e.status === 422) throw new RepoNameConflictError(org, name);
      throw e;
    }

    // 3. generate is async (202); contents may 404 briefly. Wait for it so
    //    upsertEnvExample can run immediately after.
    for (let i = 0; i < 3; i++) {
      await sleep(2000);
      try {
        await this.octokit.repos.get({ owner: org, repo: name });
        break;
      } catch (e: any) {
        if (e.status !== 404) throw e;
        if (i === 2) {
          this.logger.warn(`Repo ${org}/${name} not ready after 3 retries, continuing anyway`);
        }
      }
    }
    return { cloneUrl: gen.clone_url, generated: true };
  }

  /**
   * Upsert placeholder lines into `.env.example` of `org/repo`. Only appends
   * lines whose env-var key is not already present in the file — never
   * overwrites template content. Idempotent across retries. When the file
   * does not exist (404), it is created.
   *
   * `placeholderLines` are comment-form lines like `# NIGHTWATCH_TOKEN=...`
   * (no real secrets); the caller assembles them.
   */
  async upsertEnvExample(org: string, repo: string, placeholderLines: string[]): Promise<void> {
    if (placeholderLines.length === 0) return;

    let sha: string | undefined;
    let existing = "";
    try {
      const { data } = await this.octokit.repos.getContent({
        owner: org,
        repo,
        path: ".env.example",
      });
      // Content API returns an array for directories; we only care about files.
      if (!Array.isArray(data) && data.type === "file") {
        sha = data.sha;
        existing = Buffer.from(data.content, "base64").toString("utf-8");
      }
    } catch (e: any) {
      if (e.status !== 404) throw e;
      // 404 → file does not exist yet; create it below.
    }

    const existingKeys = extractEnvKeys(existing);
    const toAdd = placeholderLines.filter((line) => {
      const key = extractKeyFromLine(line);
      return key && !existingKeys.has(key);
    });
    if (toAdd.length === 0) return;

    const separator = existing && !existing.endsWith("\n") ? "\n" : "";
    const updated = existing + separator + toAdd.join("\n") + "\n";

    await this.octokit.repos.createOrUpdateFileContents({
      owner: org,
      repo,
      path: ".env.example",
      message: "chore: add monitoring credential placeholders",
      content: Buffer.from(updated).toString("base64"),
      sha,
    });
  }

  /**
   * Best-effort repo deletion. 404 is ignored (already gone); other errors
   * propagate. Used by teardown for FAILED/stuck-provisioning cleanup.
   */
  async deleteRepo(org: string, repo: string): Promise<void> {
    try {
      await this.octokit.repos.delete({ owner: org, repo });
    } catch (e: any) {
      if (e.status !== 404) throw e;
    }
  }
}
